//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECAirlinesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.RESERVATIONs = new HashSet<RESERVATION>();
        }
    
        public string CLIENT_ID { get; set; }
        public string CLIENT_FNAME { get; set; }
        public string CLIENT_LNAME { get; set; }
        public string CLIENT_UID { get; set; }
        public string CLIENT_PHONENO { get; set; }
        public string CLIENT_CARDNO { get; set; }
        public Nullable<int> CLIENT_MILES { get; set; }
        public string CLIENT_EMAIL { get; set; }
        public string CLIENT_PASSWRD { get; set; }
        public int UNIVERSITY_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVATION> RESERVATIONs { get; set; }
        public virtual UNIVERSITY UNIVERSITY { get; set; }
    }
}
