//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECAirlinesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLIGHT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FLIGHT()
        {
            this.FROUTEs = new HashSet<FROUTE>();
            this.RESERVATIONs = new HashSet<RESERVATION>();
        }
    
        public int FLIGHT_ID { get; set; }
        public int PLANE_ID { get; set; }
        public string ORIGIN_AIRPORT { get; set; }
        public string DESTINATION_AIRPORT { get; set; }
        public string FSTATUS { get; set; }
    
        public virtual AIRPLANE AIRPLANE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FROUTE> FROUTEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVATION> RESERVATIONs { get; set; }
    }
}
