//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECAirlinesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PILOT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PILOT()
        {
            this.AIRPLANEs = new HashSet<AIRPLANE>();
        }
    
        public int PILOT_ID { get; set; }
        public string PILOT_FNAME { get; set; }
        public string PILOT_LNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIRPLANE> AIRPLANEs { get; set; }
    }
}
