//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECAirlinesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
        public int RESERVATION_ID { get; set; }
        public int TICKET_COUNT { get; set; }
        public int LUGGAGE_COUNT { get; set; }
        public string SEATS { get; set; }
        public string CHECKIN { get; set; }
        public string T_TYPE { get; set; }
        public int PRICE { get; set; }
        public string CLIENT_ID { get; set; }
        public int FLIGHT_ID { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual FLIGHT FLIGHT { get; set; }
    }
}
